CREATE TABLE IF NOT EXISTS ayudas (
    minimis TEXT,
    nombre TEXT,
    linea TEXT,
    fecha_inicio TEXT,
    fecha_fin TEXT,
    objetivo TEXT,
    beneficiarios TEXT,
    area TEXT,
    presupuesto_minimo TEXT,
    presupuesto_maximo TEXT,
    duracion_minima TEXT,
    duracion_maxima TEXT,
    intensidad_subvencion TEXT,
    intensidad_prestamo TEXT,
    tipo_financiacion TEXT,
    forma_plazo_cobro TEXT,
    region_aplicacion TEXT,
    tipo_consorcio TEXT,
    costes_elegibles TEXT,
    link_ficha_tecnica TEXT,
    link_orden_bases TEXT,
    link_convocatoria TEXT,
    id_vectorial TEXT,
    id TEXT PRIMARY KEY,
    organismo TEXT,
    año TEXT
);

CREATE TABLE IF NOT EXISTS ayudas_ref (
    id TEXT PRIMARY KEY,
    organismo_ref INTEGER[],
    nombre_ref INTEGER[],
    fecha_inicio_ref INTEGER[],
    fecha_fin_ref INTEGER[],
    objetivo_ref INTEGER[],
    beneficiarios_ref INTEGER[],
    año_ref INTEGER[],
    presupuesto_minimo_ref INTEGER[],
    presupuesto_maximo_ref INTEGER[],
    duracion_minima_ref INTEGER[],
    duracion_maxima_ref INTEGER[],
    tipo_financiacion_ref INTEGER[],
    forma_plazo_cobro_ref INTEGER[],
    minimis_ref INTEGER[],
    region_aplicacion_ref INTEGER[],
    intensidad_subvencion_ref INTEGER[],
    intensidad_prestamo_ref INTEGER[],
    tipo_consorcio_ref INTEGER[],
    costes_elegibles_ref INTEGER[]
);
