CREATE TABLE IF NOT EXISTS ayudas (
    minimis TEXT,
    nombre TEXT,
    linea TEXT,
    fecha_inicio TEXT,
    fecha_fin TEXT,
    objetivo TEXT,
    beneficiarios TEXT,
    area TEXT,
    presupuesto_minimo TEXT,
    presupuesto_maximo TEXT,
    duracion_minima TEXT,
    duracion_maxima TEXT,
    intensidad_subvencion TEXT,
    intensidad_prestamo TEXT,
    tipo_financiacion TEXT,
    forma_plazo_cobro TEXT,
    region_aplicacion TEXT,
    tipo_consorcio TEXT,
    costes_elegibles TEXT,
    link_ficha_tecnica TEXT,
    link_orden_bases TEXT,
    link_convocatoria TEXT,
    id_vectorial TEXT,
    id TEXT PRIMARY KEY,
    organismo TEXT,
    año TEXT
);
